export default {
  // 支持值为 Object 和 Array
  'GET /mock/users': { users: [1,2] },
  'GET /haierp1/web/index.js': function(req, res) {
    res.redirect('http:\/\/localhost:8000\/index.js');
  },
  'GET /sockjs-node/info': function(req, res) {
    res.redirect('http:\/\/localhost:8000\/sockjs-node/info?t=' + new Date().getTime());
  },
  'POST /item/queryItemList': {
    "success": true,
    "msg": "",
    "data": [
      {
        "id": 27,
        "name": "测试商品1",
        "categoryId": 103,
        "categoryName": "衣服",
        "itemCode": "ITEM10018",
        "isNew": 0,
        "saleType": 0,
        "mainPic": "0",
        "itemShort": "abc",
        "enName": "abc",
        "brand": "",
        "country": 0,
        "currency": 1,
        "buySite": "",
        "origin": "",
        "weight": null,
        "unit": "",
        "source": "",
        "promotion": null,
        "contactPerson": "",
        "contactTel": "",
        "idCard": 1,
        "startDate": "2017-02-08 00:00:00",
        "endDate": "2017-02-16 00:00:00",
        "gmtCreate": "2017-02-14 14:13:14",
        "gmtModify": "2017-02-14 19:31:19",
        "userCreate": null,
        "userModify": null,
        "itemSkus": [],
        "skuList": null,
        "status": 0,
        "remark": "爱爱爱",
        "numIid": null,
        "spec": "",
        "model": "",
        "startDateStr": "2017-02-08",
        "endDateStr": "2017-02-16"
      },
      {
        "id": 28,
        "name": "Nike",
        "categoryId": 102,
        "categoryName": "小家电111",
        "itemCode": "ITEM10021",
        "isNew": 0,
        "saleType": 0,
        "mainPic": "0",
        "itemShort": "Nike",
        "enName": "Nike",
        "brand": "Hollister",
        "country": 1,
        "currency": 1,
        "buySite": "",
        "origin": "",
        "weight": null,
        "unit": "",
        "source": "",
        "promotion": null,
        "contactPerson": "",
        "contactTel": "",
        "idCard": 1,
        "startDate": null,
        "endDate": null,
        "gmtCreate": "2017-02-16 20:32:32",
        "gmtModify": "2017-02-16 20:32:49",
        "userCreate": null,
        "userModify": null,
        "itemSkus": [],
        "skuList": null,
        "status": 0,
        "remark": "",
        "numIid": null,
        "spec": "",
        "model": "",
        "startDateStr": "",
        "endDateStr": ""
      }
    ],
    "pageIndex": 1,
    "totalCount": 2,
    "totalPage": 1,
    "firstStart": 0
  },
  'POST /sku/querySkuList': {
    "success": true,
    "msg": "",
    "data": [
      {
        "id": 27,
        "name": "测试商品1",
        "categoryId": 103,
        "categoryName": "衣服",
        "itemCode": "ITEM10018",
        "isNew": 0,
        "saleType": 0,
        "mainPic": "0",
        "itemShort": "abc",
        "enName": "abc",
        "brand": "",
        "country": 0,
        "currency": 1,
        "buySite": "",
        "origin": "",
        "weight": null,
        "unit": "",
        "source": "",
        "promotion": null,
        "contactPerson": "",
        "contactTel": "",
        "idCard": 1,
        "startDate": "2017-02-08 00:00:00",
        "endDate": "2017-02-16 00:00:00",
        "gmtCreate": "2017-02-14 14:13:14",
        "gmtModify": "2017-02-14 19:31:19",
        "userCreate": null,
        "userModify": null,
        "itemSkus": [],
        "skuList": null,
        "status": 0,
        "remark": "爱爱爱",
        "numIid": null,
        "spec": "",
        "model": "",
        "startDateStr": "2017-02-08",
        "endDateStr": "2017-02-16"
      },
      {
        "id": 28,
        "name": "Nike",
        "categoryId": 102,
        "categoryName": "小家电111",
        "itemCode": "ITEM10021",
        "isNew": 0,
        "saleType": 0,
        "mainPic": "0",
        "itemShort": "Nike",
        "enName": "Nike",
        "brand": "Hollister",
        "country": 1,
        "currency": 1,
        "buySite": "",
        "origin": "",
        "weight": null,
        "unit": "",
        "source": "",
        "promotion": null,
        "contactPerson": "",
        "contactTel": "",
        "idCard": 1,
        "startDate": null,
        "endDate": null,
        "gmtCreate": "2017-02-16 20:32:32",
        "gmtModify": "2017-02-16 20:32:49",
        "userCreate": null,
        "userModify": null,
        "itemSkus": [],
        "skuList": null,
        "status": 0,
        "remark": "",
        "numIid": null,
        "spec": "",
        "model": "",
        "startDateStr": "",
        "endDateStr": ""
      }
    ],
    "pageIndex": 1,
    "totalCount": 2,
    "totalPage": 1,
    "firstStart": 0
  },
  'POST /cate/queryCateList': {
    'success': true,
    'msg': '',
    'data': [
      {
        'name': '衣服',
        'cateCode': 'ITEM10021',
        'servicesRate': '5%',
        'propName': 103,
        'remark': '无',
        'id': 1,
      },
    ],
    'pageIndex': 1,
    'totalCount': 2,
    'totalPage': 1,
    'firstStart': 0
  }
};